export { default as DashBoardIcon } from '@/components/icons/IconDashboardViwe.vue'
export { default as CategorisIcon } from '@/components/icons/IconCategories.vue'
export { default as ImgIcon } from '@/components/icons/IconImage.vue'
export { default as StatusIcon } from '@/components/icons/IconStatus.vue'
export { default as AddIcon } from '@/components/icons/IconAdd.vue'
export { default as CloseIcon } from '@/components/icons/IconClose.vue'
export { default as EditIcon } from '@/components/icons/IconEdit.vue'
export { default as DeleteIcon } from '@/components/icons/IconDelete.vue'
export { default as LoadingIcon } from '@/components/icons/IconLoading.vue'
export { default as BackIcon } from '@/components/icons/IconBack.vue'
export { default as InvoiceIcon } from '@/components/icons/IconInvoice.vue'
export { default as HomeIcon } from '@/components/icons/IconHome.vue'
export { default as LogoApp} from '../assets/images/logo.jpg'
